export const GET_DATA = "GET_DATA"
export const ADD_TO_CART = "ADD_TO_CART"
export const LOAD_MSG ="LOAD_MSG"
export const  INC_COUTN = "INC_COUTN"
export const  DECREASE_COUNT = "DECREASE_COUNT"
export const DELETE_ITEM_CART ="DELETE_ITEM_CART"